# Generated by Django 4.1.5 on 2023-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='field2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='field3',
            field=models.IntegerField(default=0),
        ),
    ]
